sudo: false

language: go

go:
  - '1.12.x'


notifications:
  email: false

git:
  depth: false

services:
  - docker

env:
  global: 
    - GO111MODULE=on

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest

before_deploy:
      make docs

deploy:
  - provider: pages
    edge: false
    github_token: ${GH_TOKEN}
    local_dir: docs/site
    skip_cleanup: true
    on:
      repo: onosproject/onos-docs
      all_branches: true

cache:
  directories:
    - $HOME/gopath/pkg/mod         # Cache the Go modules

jobs:
  include:
    - stage: build
      script:
        - make docs
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/bin/push-images; fi'