sudo: false
language: python
install:
- pip install pygments
- pip install mkdocs
- pip install mkdocs-material
script:
- git clean -f -d -x
after_success:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then chmod +x build/build_docs.sh && ./build/build_docs.sh; fi' 
