versions:
  - ver: 'v0.2'
    repos:
        - name: onos-config
          url: https://github.com/onosproject/onos-config
          tagName: master
        - name: onos-topo
          url: https://github.com/onosproject/onos-topo
          tagName:  master
        - name: onos-gui
          url: https://github.com/onosproject/onos-gui
          tagName:  master
        - name: onos-test
          url: https://github.com/onosproject/onos-test
          tagName:  master
        - name: onos-cli
          url: https://github.com/onosproject/onos-cli
          tagName:  master
        - name: onos-ztp
          url: https://github.com/onosproject/onos-ztp
          tagName:  master
  - ver: 'v0.1-onfconnect'
    repos:
        - name: onos-config
          url: https://github.com/onosproject/onos-config
          tagName: v0.1-onfconnect
        - name: onos-topo
          url: https://github.com/onosproject/onos-topo
          tagName: v0.1-onfconnect
        - name: onos-gui
          url: https://github.com/onosproject/onos-gui
          tagName: v0.1-onfconnect
        - name: onos-test
          url: https://github.com/onosproject/onos-test
          tagName: v0.1-onfconnect
  - ver: 'v0.2-onfconnect'
    repos:
        - name: onos-config
          url: https://github.com/onosproject/onos-config
          tagName: v0.1-onfconnect
        - name: onos-topo
          url: https://github.com/onosproject/onos-topo
          tagName: v0.1-onfconnect
        - name: onos-gui
          url: https://github.com/onosproject/onos-gui
          tagName: v0.1-onfconnect
        - name: onos-test
          url: https://github.com/onosproject/onos-test
          tagName: v0.1-onfconnect
  - ver: 'v0.3-onfconnect'
    repos:
        - name: onos-config
          url: https://github.com/onosproject/onos-config
          tagName: v0.1-onfconnect
        - name: onos-topo
          url: https://github.com/onosproject/onos-topo
          tagName: v0.1-onfconnect
        - name: onos-gui
          url: https://github.com/onosproject/onos-gui
          tagName: v0.1-onfconnect
        - name: onos-test
          url: https://github.com/onosproject/onos-test
          tagName: v0.1-onfconnect
  - ver: 'v0.3-onfconnect'
    repos:
        - name: onos-config
          url: https://github.com/onosproject/onos-config
          tagName: v0.1-onfconnect
        - name: onos-topo
          url: https://github.com/onosproject/onos-topo
          tagName: v0.1-onfconnect
        - name: onos-gui
          url: https://github.com/onosproject/onos-gui
          tagName: v0.1-onfconnect
        - name: onos-test
          url: https://github.com/onosproject/onos-test
          tagName: v0.1-onfconnect
  - ver: 'v0.4-onfconnect'
    repos:
        - name: onos-config
          url: https://github.com/onosproject/onos-config
          tagName: v0.1-onfconnect
        - name: onos-topo
          url: https://github.com/onosproject/onos-topo
          tagName: v0.1-onfconnect
        - name: onos-gui
          url: https://github.com/onosproject/onos-gui
          tagName: v0.1-onfconnect
        - name: onos-test
          url: https://github.com/onosproject/onos-test
          tagName: v0.1-onfconnect

LatestVersion: "v0.2"