nav:
- ONOS: README.md
- Developers:
  - Contacts and Calenders: developers/community-info.md
  - Development Prerequisites: developers/prerequisites.md
  - Developer Workflow: developers/dev_workflow.md
  - Contribution Guidelines: developers/contributing.md
  - GoDoc Pages: developers/godocs.md
- Configuration Subsystem:
  - An Introduction to Configuration Susbsytem: onos-config/docs/README.md
  - How To Build Configuration Subsystem?: onos-config/docs/build.md
  - How To Run Configuration Subsystem?: onos-config/docs/run.md
  - How To Debug Configuration Subsystem?: onos-config/docs/debugging.md
  - Administrative And Diagnostic CLI: onos-config/docs/cli.md
  - Extending Configuration Subsystem With Model Plugins: onos-config/docs/modelplugin.md
  - Northbound gNMI Service: onos-config/docs/gnmi.md
  - gNMI Extensions: onos-config/docs/gnmi_extensions.md
  - APIs:
      - Admin API: onos-config/docs/api/admin.md
      - Diagnostic API: onos-config/docs/api/diags.md
      - Types:
          - Common Change Types: onos-config/docs/api/types_change.md
          - Device Change Types: onos-config/docs/api/types_change_device.md
          - Network Change Types: onos-config/docs/api/types_change_network.md
          - Common Snapshot Types: onos-config/docs/api/types_snapshot.md
          - Device Snapshot Types: onos-config/docs/api/types_snapshot_device.md
          - Network Snapshot Types: onos-config/docs/api/types_snapshot_network.md
- Topology Subsystem:
  - How To Use Topology Subsystem CLI?: onos-topo/docs/cli.md
  - APIs:
      - Admin API: onos-topo/docs/api/admin.md
      - Diagnostic API: onos-topo/docs/api/diags.md
      - Device API: onos-topo/docs/api/device.md
- Command Line Interface Subsystem (CLI):
  - How To Install and Run CLI Subsystem?: onos-cli/docs/setup.md
  - ONOS CLI Commands: onos-cli/docs/cli/onos.md
- Zero-Touch Provisioning (ZTP) Subsystem:
  - How To Install And Run ZTP?: onos-ztp/docs/setup.md
  - APIs:
      - Admin API: onos-ztp/docs/api/admin.md
- Test Tools:
  - How To Install and Run ONIT?: onos-test/docs/setup.md
  - How To Use ONIT?: onos-test/docs/run.md
  - How To Write and Run Tests?: onos-test/docs/testing.md
- Graphical User Interface (GUI):
  - ONOS-GUI Subsystem: onos-gui/docs/README.md
  - Configuration GUI: onos-gui/docs/config-gui.md
  - GUI Architecture: onos-gui/docs/architecture.md
  - GUI Development Prerequisites: onos-gui/docs/prerequisites.md
  - How To Run ONOS GUI?: onos-gui/docs/run.md
